name: cannachange
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  mobx_codegen: ^2.0.1+3
  flutter_mobx: ^2.0.0
  mobx: ^2.0.1
  dio: ^4.0.0
  intl: ^0.17.0
  easy_sidemenu: ^0.1.1+1
  pedantic: ^1.11.0
  json_annotation: ^4.4.0
  json_serializable: ^6.1.1
  cupertino_icons: ^1.0.2
  freezed_annotation: ^0.14.1
  get_storage: ^2.0.2
  get_it: ^7.1.3
  webview_flutter: ^3.0.0
  flutter_svg_provider: ^1.0.2
  auto_route: ^3.2.1
  analyzer: ^2.5.0
  overlay_support: ^1.2.1
  flutter_svg: ^1.0.3
  image_picker: ^0.8.4+5
  file_picker: ^4.3.3
  flutter_launcher_icons: ^0.9.2
  nil: ^1.1.1
  path_provider: ^2.0.6
  url_launcher: ^6.0.18
  firebase_core: ^1.11.0
  firebase_messaging: ^11.2.5
  google_maps_flutter: ^2.1.1
  infinite_scroll_pagination: ^3.1.0
  qr_code_scanner: ^0.6.1
  qr_flutter: ^4.0.0
  font_awesome_flutter: ^9.2.0
  flutter_local_notifications: ^9.2.0



scripts:
  build: flutter pub run build_runner build --delete-conflicting-outputs
  build:watch: flutter pub run build_runner watch --delete-conflicting-outputs

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/launcher_icon.png"


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  build_runner: ^2.1.7
  freezed: ^0.14.1+3
  auto_route_generator: ^3.2.1
  import_sorter: ^4.5.0


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.

flutter:
  uses-material-design: true
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato/Lato-Black.ttf
        - asset: assets/fonts/Lato/Lato-BlackItalic.ttf
        - asset: assets/fonts/Lato/Lato-Bold.ttf
        - asset: assets/fonts/Lato/Lato-BoldItalic.ttf
        - asset: assets/fonts/Lato/Lato-Italic.ttf
        - asset: assets/fonts/Lato/Lato-Light.ttf
        - asset: assets/fonts/Lato/Lato-LightItalic.ttf
        - asset: assets/fonts/Lato/Lato-Regular.ttf
        - asset: assets/fonts/Lato/Lato-Thin.ttf
        - asset: assets/fonts/Lato/Lato-ThinItalic.ttf

  assets:
    - assets/icons/
    - assets/fonts/
    - assets/illustrations/
    - assets/images/

